plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.siemens.train'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    // REST API
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JDBC database access
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    // MySQL driver
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Password hashing
    implementation 'org.mindrot:jbcrypt:0.4'

    // Email sending
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}